
--pickups
add_entity_to_list("data/entities/items/pickup/heart.xml","heart","pickups")
add_entity_to_list("data/entities/items/pickup/heart_better.xml","strong heart","pickups")
add_entity_to_list("data/entities/items/pickup/heart_evil.xml","cursed heart","pickups")
add_entity_to_list("data/entities/items/pickup/heart_fullhp.xml","HP restore","pickups")
add_entity_to_list("data/entities/items/pickup/heart_fullhp_temple.xml","HP restore and increase","pickups")

add_entity_to_list("data/entities/items/pickup/spell_refresh.xml","spell refresher","pickups")
add_entity_to_list("data/entities/items/pickup/utility_box.xml","utility box","pickups")
add_entity_to_list("data/entities/items/pickup/chest_random.xml","treasure chest","pickups")
add_entity_to_list("data/entities/items/pickup/chest_random_super.xml","great treasure chest","pickups")

add_entity_to_list("data/entities/items/pickup/essence_air.xml","essence of air","pickups")
add_entity_to_list("data/entities/items/pickup/essence_fire.xml","essence of fire","pickups")
add_entity_to_list("data/entities/items/pickup/essence_laser.xml","essence of earth","pickups")
add_entity_to_list("data/entities/items/pickup/essence_water.xml","essence of water","pickups")
add_entity_to_list("data/entities/items/pickup/essence_alcohol.xml","essence of spirits","pickups")

add_entity_to_list("data/entities/items/pickup/greed_curse.xml","curse of greed","pickups")




--items
add_entity_to_list("data/entities/items/pickup/brimstone.xml","kiuaskivi (fire stone)","items")
add_entity_to_list("data/entities/items/pickup/thunderstone.xml","ukkoskivi (thunder stone)","items")
add_entity_to_list("data/entities/items/pickup/waterstone.xml","vuoksikivi (water stone)","items")
add_entity_to_list("data/entities/items/pickup/stonestone.xml","tannerkivi (earth stone)","items")
add_entity_to_list("data/entities/items/pickup/poopstone.xml","kakkakikkare (poop stone)","items")
add_entity_to_list("data/entities/items/pickup/sun/sunseed.xml","auringonsiemen (sun seed)","items")

add_entity_to_list("data/entities/items/pickup/broken_wand.xml","broken wand","items")

add_entity_to_list("data/entities/items/pickup/summon_portal_broken.xml","broken spell","items")

add_entity_to_list("data/entities/items/pickup/evil_eye.xml","paha silmä (evil eye)","items")

add_entity_to_list("data/entities/items/pickup/safe_haven.xml","kammi (save haven)","items")

add_entity_to_list("data/entities/items/pickup/moon.xml","kuu (moon)","items")

add_entity_to_list("data/entities/items/pickup/physics_gold_orb.xml","shiny orb","items")
add_entity_to_list("data/entities/items/pickup/physics_gold_orb_greed.xml","cruel orb","items")

add_entity_to_list("data/entities/items/pickup/physics_die.xml","chaos die","items")
add_entity_to_list("data/entities/items/pickup/physics_greed_die.xml","greed die","items")

add_entity_to_list("data/entities/items/pickup/gourd.xml","refreshing gourd","items")

add_entity_to_list("data/entities/items/pickup/beamstone.xml","sädekvi (beamstone)","items")

add_entity_to_list("data/entities/items/pickup/musicstone.xml","kuulokivi (music stone)","items")

add_entity_to_list("data/entities/items/pickup/wandstone.xml","sauvan ydin (wand stone)","items")

add_entity_to_list("data/entities/items/pickup/runestones/runestone_slow.xml","runestone of weight","items")
add_entity_to_list("data/entities/items/pickup/runestones/runestone_disc.xml","runestone of edges","items")
add_entity_to_list("data/entities/items/pickup/runestones/runestone_fireball.xml","runestone of fire","items")
add_entity_to_list("data/entities/items/pickup/runestones/runestone_laser.xml","runestone of light","items")
add_entity_to_list("data/entities/items/pickup/runestones/runestone_lava.xml","runestone of lava","items")
add_entity_to_list("data/entities/items/pickup/runestones/runestone_metal.xml","runestone of metal","items")
add_entity_to_list("data/entities/items/pickup/runestones/runestone_null.xml","runestone of emptiness","items")





--enemies
add_entity_to_list("data/entities/animals/acidshooter.xml","Hiekko Happonuljaska (Weak Acid spitter)","enemies")
add_entity_to_list("data/entities/animals/acidshooter_weak.xml","Happonuljaska (Acid spitter)","enemies")
add_entity_to_list("data/entities/animals/alchemist.xml","Puistokemisi (Alchemist hiisi)","enemies")
add_entity_to_list("data/entities/animals/ant.xml","Murkku (Ant)","enemies")
add_entity_to_list("data/entities/animals/assassin.xml","Salamurhaajarobotti (Assasin)","enemies")
add_entity_to_list("data/entities/animals/barfer.xml","Turvonnu velho (Bloated Wizard)","enemies")
add_entity_to_list("data/entities/animals/basebot_hidden.xml","Vakoilija (Spy)","enemies")
add_entity_to_list("data/entities/animals/basebot_neutralizer.xml","Pysäyttäjä (Stopper)","enemies")
add_entity_to_list("data/entities/animals/basebot_sentry.xml","Tarkkailija (Observer)","enemies")
add_entity_to_list("data/entities/animals/basebot_soldier.xml","Teloittaja (Executioner)","enemies")
add_entity_to_list("data/entities/animals/bat.xml","Lepakko (Bat)","enemies")
add_entity_to_list("data/entities/animals/berserkspirit.xml","Viha-Aave (Anger Spirit)","enemies")
add_entity_to_list("data/entities/animals/bigbat.xml","Suurlepakko (Large Bat)","enemies")
add_entity_to_list("data/entities/animals/bigfirebug.xml","Suurtulikärpänen (Greater firefly)","enemies")
add_entity_to_list("data/entities/animals/bigzombie.xml","Mätänevä ruumis (Rotting Corpse)","enemies")
add_entity_to_list("data/entities/animals/blob.xml","Kiukkumöykky (Angry Blob)","enemies")
add_entity_to_list("data/entities/animals/bloodcrystal_physics.xml","Verikristalli (Blood Crystal)","enemies")
add_entity_to_list("data/entities/animals/bloom.xml","Puska (Bloom)","enemies")
add_entity_to_list("data/entities/animals/chest_leggy.xml","Jalkamatkatavara (Leggy Mimic)","enemies")
add_entity_to_list("data/entities/animals/chest_mimic.xml","Matkija (Mimic)","enemies")
add_entity_to_list("data/entities/animals/confusespirit.xml","Utu-Aave (Fog Spirit)","enemies")
add_entity_to_list("data/entities/animals/coward.xml","Raukka (Coward)","enemies")
add_entity_to_list("data/entities/animals/crystal_physics.xml","Kirottu kristalli (Cursed Crystal)","enemies")
--add_entity_to_list("data/entities/animals/darkghost.xml","? (?)","enemies") --unused enemy
add_entity_to_list("data/entities/animals/deer.xml","Nelikoipi (Deer)","enemies")
--add_entity_to_list("data/entities/animals/drone.xml","Lennokki (Drone)","enemies") --unused enemy
add_entity_to_list("data/entities/animals/drone_lasership.xml","Jättilaser-lennokki (Giant Laser-Drone)","enemies")
add_entity_to_list("data/entities/animals/drone_physics.xml","Lennokki (Drone)","enemies")
add_entity_to_list("data/entities/animals/drone_shield.xml","Turvalennokki (Safety Drone)","enemies")
add_entity_to_list("data/entities/animals/duck.xml","Ankka (Duck)","enemies")
add_entity_to_list("data/entities/animals/eel.xml","Nahkiainen (Lamprey)","enemies")
add_entity_to_list("data/entities/animals/elk.xml","Poro (Reindeer)","enemies")
add_entity_to_list("data/entities/animals/enlightened_alchemist.xml","Valaistunut alkemisti (enlightened alchemist)","enemies")
add_entity_to_list("data/entities/animals/ethereal_being.xml","Olematon (Non-existent)","enemies")
add_entity_to_list("data/entities/animals/failed_alchemist.xml","Kadotettu alkemisti (Damned Alchemist)","enemies")
add_entity_to_list("data/entities/animals/failed_alchemist_b.xml","Epäalkemisti (Non-alchemist)","enemies")
add_entity_to_list("data/entities/animals/firebug.xml","Pikkutulikärpänen (Firefly)","enemies")
add_entity_to_list("data/entities/animals/firemage.xml","Eldari (Hellfire Mage)","enemies")
add_entity_to_list("data/entities/animals/firemage_weak.xml","Stendari (Fire Mage)","enemies")
add_entity_to_list("data/entities/animals/fireskull.xml","Liekkiö (Fire Spirit)","enemies")
add_entity_to_list("data/entities/animals/fireskull_weak.xml","Liekkiö (Fire Spirit) (weak)","enemies")
add_entity_to_list("data/entities/animals/fish.xml","Eväkäs (Fish)","enemies")
add_entity_to_list("data/entities/animals/fish_large.xml","Suureväkäs (Large fish)","enemies")
add_entity_to_list("data/entities/animals/flamer.xml","Liekkari (Flamer)","enemies")
add_entity_to_list("data/entities/animals/fly.xml","Amppari (Wasp)","enemies")

add_entity_to_list("data/entities/animals/frog.xml","Konna (Toad)","enemies")
add_entity_to_list("data/entities/animals/frog_big.xml","Jättikonna (Big Toad)","enemies")
add_entity_to_list("data/entities/animals/fungus.xml","Laahustussieni (Shuffling Fungus)","enemies")
add_entity_to_list("data/entities/animals/fungus_big.xml","Nuijamalikka (Club-foot)","enemies")
add_entity_to_list("data/entities/animals/fungus_giga.xml","Huhtasieni (Pollen Morel)","enemies")
add_entity_to_list("data/entities/animals/fungus_tiny.xml","Myrkkynääpikkä (Funeral Bell)","enemies")
add_entity_to_list("data/entities/animals/gazer.xml","Helvetinkatse (Hell Gazer)","enemies")
add_entity_to_list("data/entities/animals/ghost.xml","Houre (Delirium)","enemies")
add_entity_to_list("data/entities/animals/ghoul.xml","Sylkyri (Spitter)","enemies")
add_entity_to_list("data/entities/animals/giant.xml","Hiidenkivi (Rock Giant)","enemies")
add_entity_to_list("data/entities/animals/giantshooter.xml","Äitinuljaska (Mother Slime)","enemies")
add_entity_to_list("data/entities/animals/giantshooter_weak.xml","Heikko äitinuljaska (Weak Mother Slime)","enemies")
add_entity_to_list("data/entities/animals/goblin_bomb.xml","Sähikäismenninkäinen (Firecracker Goblin)","enemies")
add_entity_to_list("data/entities/animals/healerdrone_physics.xml","Korjauslennokki (Repair Drone)","enemies")
add_entity_to_list("data/entities/animals/icemage.xml","Pakkasukko (Old Man Winter)","enemies")
add_entity_to_list("data/entities/animals/icer.xml","Jäähdytyslaite (Icer)","enemies")
add_entity_to_list("data/entities/animals/iceskull.xml","Jäätiö (Ice Spirit)","enemies")
add_entity_to_list("data/entities/animals/lasershooter.xml","Mulkkio (Gazer)","enemies")
add_entity_to_list("data/entities/animals/longleg.xml","Hämis","enemies")
add_entity_to_list("data/entities/animals/lurker.xml","Varjokupla (Shadow Bubble)","enemies")
add_entity_to_list("data/entities/animals/maggot.xml","Toukka (Maggot)","enemies")
add_entity_to_list("data/entities/animals/meatmaggot.xml","Mätäryömijä (Putrid Crawler)","enemies")
add_entity_to_list("data/entities/animals/mimic_potion.xml","Henkevä potu (Potion Mimic)","enemies")
add_entity_to_list("data/entities/animals/miner.xml","Tappurahiisi (Miner Hiisi)","enemies")
add_entity_to_list("data/entities/animals/miner_chef.xml","Kokkihiisi (Hiisi Chef)","enemies")
add_entity_to_list("data/entities/animals/miner_fire.xml","Tulihiisi (Fire Hiisi)","enemies")
add_entity_to_list("data/entities/animals/miner_hell.xml","Hornantappurahiisi (Hell Miner Hiisi)","enemies")
add_entity_to_list("data/entities/animals/miner_santa.xml","Jouluhiisi (Christmas Hiisi)","enemies")
add_entity_to_list("data/entities/animals/miner_weak.xml","Tappurahiisiläinen (Weak Hiisi miner)","enemies")
add_entity_to_list("data/entities/animals/miniblob.xml","Möykky (Blob)","enemies")
add_entity_to_list("data/entities/animals/missilecrab.xml","Heinäsirkka (Cricket)","enemies")
add_entity_to_list("data/entities/animals/monk.xml","Munkki (Monk)","enemies")
add_entity_to_list("data/entities/animals/necrobot.xml","Tuonelankone (Necrobot)","enemies")
add_entity_to_list("data/entities/animals/necrobot_super.xml","Marraskone (Super Necrobot)","enemies")
add_entity_to_list("data/entities/animals/necromancer.xml","Hahmonvaihtaja (Shapechanger)","enemies")
add_entity_to_list("data/entities/animals/necromancer_shop.xml","Stevari (Guard)","enemies")
add_entity_to_list("data/entities/animals/pebble_physics.xml","Lohkare (Rock Spirit)","enemies")
add_entity_to_list("data/entities/animals/phantom_a.xml","(Spiraalikalma (Spiral Phantom)","enemies")
add_entity_to_list("data/entities/animals/phantom_b.xml","Kiukkukalma (Angry Phantom)","enemies")
add_entity_to_list("data/entities/animals/playerghost.xml","Kummitus (Ghost)","enemies")
add_entity_to_list("data/entities/animals/rat.xml","Rotta (Rat)","enemies")
add_entity_to_list("data/entities/animals/roboguard.xml","Robottikyttä (Robo-Cop)","enemies")
add_entity_to_list("data/entities/animals/roboguard_big.xml","Kyrmyniska (Hunchback)","enemies")
add_entity_to_list("data/entities/animals/scavenger_clusterbomb.xml","Isohiisi (Hiisi Bomber)","enemies")
add_entity_to_list("data/entities/animals/scavenger_glue.xml","Liimahiisi (Glue Hiisi)","enemies")
add_entity_to_list("data/entities/animals/scavenger_grenade.xml","Kranuhiisi (Hiisi Grenadier)","enemies")
add_entity_to_list("data/entities/animals/scavenger_heal.xml","Parantajahiisi (Hiisi Healer)","enemies")
add_entity_to_list("data/entities/animals/scavenger_invis.xml","Häivehiisi (Stealth Hiisi)","enemies")
add_entity_to_list("data/entities/animals/scavenger_leader.xml","Toimari (Hiisi Leader)","enemies")
add_entity_to_list("data/entities/animals/scavenger_mine.xml","Miinankylväjä (Hiisi Mine Thrower)","enemies")
add_entity_to_list("data/entities/animals/scavenger_poison.xml","Myrkkyhiisi (Hiisi Poisoner)","enemies")
add_entity_to_list("data/entities/animals/scavenger_shield.xml","Kilpihiisi (Shield Hiisi)","enemies")
add_entity_to_list("data/entities/animals/scavenger_smg.xml","Rynkkyhiisi (Hiisi Gunner)","enemies")
add_entity_to_list("data/entities/animals/scorpion.xml","Skorpioni (Scorpion)","enemies")
add_entity_to_list("data/entities/animals/scorpion_watchtower.xml","Skorpioni (Scorpion) (watchtower)","enemies")
add_entity_to_list("data/entities/animals/shaman.xml","Märkiäinen (Swampling)","enemies")
add_entity_to_list("data/entities/animals/sheep.xml","Lammas (Sheep)","enemies")
add_entity_to_list("data/entities/animals/sheep_bat.xml","Lentolammas (Flying Sheep)","enemies")
add_entity_to_list("data/entities/animals/sheep_fly.xml","Suhiseva lammas (Buzzing sheep)","enemies")
add_entity_to_list("data/entities/animals/shooterflower.xml","Plasmakukka (Plasma Flower)","enemies")
add_entity_to_list("data/entities/animals/shotgunner.xml","Haulikkohiisi (Shotgun Hiisi)","enemies")
add_entity_to_list("data/entities/animals/shotgunner_hell.xml","Hornahiisi (Hell Shotgun Hiisi)","enemies")
add_entity_to_list("data/entities/animals/shotgunner_weak.xml","Heikko haulikkohiisi (Weak shotgun Hiisi)","enemies")
add_entity_to_list("data/entities/animals/skullfly.xml","Kallokärpänen (Skull Fly)","enemies")
add_entity_to_list("data/entities/animals/skullrat.xml","Kallorotta (Skull Rat)","enemies")
add_entity_to_list("data/entities/animals/skycrystal_physics.xml","Taivaskristalli (Celestial Crystal)","enemies")
add_entity_to_list("data/entities/animals/skygazer.xml","Taivaankatse (Sky Gazer)","enemies")
add_entity_to_list("data/entities/animals/slimeshooter.xml","limanuljaska (Toxic Slime)","enemies")
add_entity_to_list("data/entities/animals/slimeshooter_weak.xml","Heikko limanuljaska (Weak Toxic Slime)","enemies")
add_entity_to_list("data/entities/animals/slimespirit.xml","Neva-Aave (Bog Spirit)","enemies")
add_entity_to_list("data/entities/animals/sniper.xml","Snipuhiisi (Hiisi Sniper)","enemies")
add_entity_to_list("data/entities/animals/sniper_hell.xml","Hornasnipuhiisi (Hiisi Hell Sniper)","enemies")
add_entity_to_list("data/entities/animals/spearbot.xml","Peitsivartija (Lance Sentry)","enemies")
add_entity_to_list("data/entities/animals/spitmonster.xml","Helvetin sylkijä (Hell Spitter)","enemies")
add_entity_to_list("data/entities/animals/statue.xml","Patsas (Statue)","enemies")
add_entity_to_list("data/entities/animals/statue_physics.xml","Hohtonaamio (Glowing Mask)","enemies")
add_entity_to_list("data/entities/animals/tank.xml","KK-Tankki","enemies")
add_entity_to_list("data/entities/animals/tank_rocket.xml","IT-Tankki","enemies")
add_entity_to_list("data/entities/animals/tank_super.xml","Laser-Tankki","enemies")
add_entity_to_list("data/entities/animals/tentacler.xml","Turso (Tentacler)","enemies")
add_entity_to_list("data/entities/animals/tentacler_small.xml","Pikkuturso (Small Tentacler)","enemies")
add_entity_to_list("data/entities/animals/thundermage.xml","Ukko (Thunder Mage)","enemies")
add_entity_to_list("data/entities/animals/thundermage_big.xml","Suur-Ukko (Great Thunder Mage)","enemies")
add_entity_to_list("data/entities/animals/thunderskull.xml","Sähkiö (Thunder Spirit)","enemies")
add_entity_to_list("data/entities/animals/turret_left.xml","Torjuntalaite (Turret) (left)","enemies")
add_entity_to_list("data/entities/animals/turret_right.xml","Torjuntalaite (Turret) (right)","enemies")
add_entity_to_list("data/entities/animals/ultimate_killer.xml","Kauhuhirviö (Horror Monster)","enemies")
add_entity_to_list("data/entities/animals/wand_ghost.xml","Taikasauva (Magic Wand)","enemies")
add_entity_to_list("data/entities/animals/weakspirit.xml","Kaamo-Aave (Depression Spirit)","enemies")
add_entity_to_list("data/entities/animals/wizard_dark.xml","Sokaisunmestari (Master of Blinding)","enemies")
add_entity_to_list("data/entities/animals/wizard_hearty.xml","Haavoittajamestari (Master of Wounding)","enemies")
add_entity_to_list("data/entities/animals/wizard_homing.xml","Kohdennusmestari (Master of Homing)","enemies")
add_entity_to_list("data/entities/animals/wizard_neutral.xml","Maadoittajamestari (Master of Grounding)","enemies")
add_entity_to_list("data/entities/animals/wizard_poly.xml","Muodonmuutosmestari (Master of Polymorphing)","enemies")
add_entity_to_list("data/entities/animals/wizard_returner.xml","Palauttajamestari (Master of Returning)","enemies")
add_entity_to_list("data/entities/animals/wizard_swapper.xml","Vaihdosmestari (Master of Exchanging)","enemies")
add_entity_to_list("data/entities/animals/wizard_tele.xml","Siirtäjämestari (Master of Teleportation)","enemies")
add_entity_to_list("data/entities/animals/wizard_twitchy.xml","Sätkymestari (Master of Twitching)","enemies")
add_entity_to_list("data/entities/animals/wizard_weaken.xml","Turvattomuusmestari (Master of Vulnerability)","enemies")
add_entity_to_list("data/entities/animals/wolf.xml","Susi (Wolf)","enemies")
add_entity_to_list("data/entities/animals/worm.xml","Mato (Worm)","enemies")
add_entity_to_list("data/entities/animals/worm_big.xml","Jättimato (Giant worm)","enemies")
add_entity_to_list("data/entities/animals/worm_end.xml","Helvetinmato (Hell Worm)","enemies")
add_entity_to_list("data/entities/animals/worm_skull.xml","Kalmamato (Death Worm)","enemies")
add_entity_to_list("data/entities/animals/worm_tiny.xml","Pikkumato (small worm)","enemies")
add_entity_to_list("data/entities/animals/wraith.xml","Hyypiö (Creep)","enemies")
add_entity_to_list("data/entities/animals/wraith_glowing.xml","Hohtava hyypiö (Glowing Creep)","enemies")
add_entity_to_list("data/entities/animals/wraith_storm.xml","Ukkoshyypiö (Thunder Creep)","enemies")
add_entity_to_list("data/entities/animals/zombie.xml","Hurtta (Hound)","enemies")
add_entity_to_list("data/entities/animals/zombie_weak.xml","Heikkohurtta (Weak Hound)","enemies")





--add_entity_to_list("data/entities/animals/mimic_physics.xml","Hämis vase","props")



-- bosses
add_entity_to_list("data/entities/animals/boss_centipede/boss_centipede.xml","Kolmisilmä (Three-Eye)","bosses")
add_entity_to_list("data/entities/animals/boss_centipede/boss_centipede_minion.xml","Kolmisilmän apuri (Three-Eye's Helper)","bosses")
add_entity_to_list("data/entities/animals/boss_alchemist/boss_alchemist.xml","Ylialkemisti (High Alchemist)","bosses")
add_entity_to_list("data/entities/animals/parallel/alchemist/parallel_alchemist.xml","Alkemistin Varjo (Alchemist's Shadow)","bosses")
add_entity_to_list("data/entities/animals/boss_pit/boss_pit.xml","Sauvojen tuntija (Connoisseur of Wands)","bosses")
add_entity_to_list("data/entities/animals/parallel/tentacles/parallel_tentacles.xml","Kolmisilmän Kätyri (Three-eye's Minion)","bosses")
add_entity_to_list("data/entities/animals/boss_wizard/boss_wizard.xml","Mestarien mestari (Master of Masters)","bosses")
add_entity_to_list("data/entities/animals/boss_fish/fish_giga.xml","Syväolento (Creature of the Deep)","bosses")
add_entity_to_list("data/entities/animals/boss_ghost/boss_ghost.xml","Unohdettu (Forgotten)","bosses")
add_entity_to_list("data/entities/animals/boss_ghost/boss_ghost_polyp.xml","häive (Fade)","bosses")
add_entity_to_list("data/entities/animals/boss_dragon.xml","Suomuhauki (Dragon)","bosses")
add_entity_to_list("data/entities/animals/boss_limbs/boss_limbs.xml","Kolmisilmän Koipi (Three-Eye's Legs)","bosses")
add_entity_to_list("data/entities/animals/boss_limbs/slimeshooter_boss_limbs.xml","Äitilimanuljaska (Guardian Slime)","bosses")
add_entity_to_list("data/entities/animals/boss_robot/boss_robot.xml","Kolmisilmän Silmä (Three-Eye's Eye)","bosses")
add_entity_to_list("data/entities/animals/maggot_tiny/maggot_tiny.xml","Limatoukka (Slime Maggot)","bosses")
add_entity_to_list("data/entities/animals/boss_meat/boss_meat.xml","Kolmisilmän sydän (Three-Eye's Heart)","bosses")
add_entity_to_list("data/entities/animals/boss_sky/boss_sky.xml","Kivi (Stone)","bosses")
add_entity_to_list("data/entities/animals/boss_spirit/islandspirit.xml","Tapion vasalli (Tapio's Vassal)","bosses")
add_entity_to_list("data/entities/animals/boss_gate/gate_monster_c.xml","Mokke (Goalkeeper)","bosses")
add_entity_to_list("data/entities/animals/boss_gate/gate_monster_b.xml","Molari (Goalkeeper)","bosses")
add_entity_to_list("data/entities/animals/boss_gate/gate_monster_d.xml","Sevia (Goalkeeper)","bosses")
add_entity_to_list("data/entities/animals/boss_gate/gate_monster_a.xml","Veska (Goalkeeper)","bosses")

add_entity_to_list("data/entities/animals/friend.xml","Toveri (Friend)","bosses")








