--props
add_entity_to_list("data/entities/props/dummy_target.xml","Target Dummy","props","data/props_gfx/dummy_target.png")
add_entity_to_list("data/entities/props/music_machines/music_machine_00.xml","Music Machine (1)","props","data/props_gfx/music_machine.png")
add_entity_to_list("data/entities/props/music_machines/music_machine_01.xml","Music Machine (2)","props","data/props_gfx/music_machine.png")
add_entity_to_list("data/entities/props/music_machines/music_machine_02.xml","Music Machine (3)","props","data/props_gfx/music_machine.png")
add_entity_to_list("data/entities/props/music_machines/music_machine_03.xml","Music Machine (4)","props","data/props_gfx/music_machine.png")
add_entity_to_list("data/entities/props/physics_cart.xml","Cart","props","data/props_gfx/cart_top.png")
add_entity_to_list("data/entities/props/physics_minecart.xml","Minecart","props","data/props_gfx/minecart.png") 
add_entity_to_list("data/entities/props/physics_skateboard.xml","Skateboard","props","data/props_gfx/skateboard.png")
add_entity_to_list("data/entities/props/forcefield_generator.xml","Forcefield Generator","props","data/props_gfx/forcefield_generator.png")
add_entity_to_list("data/entities/props/furniture_castle_chair.xml","Castle Chair","props","data/props_gfx/furniture_castle_chair.png")
add_entity_to_list("data/entities/props/furniture_castle_divan.xml","Castle Divan","props","data/props_gfx/furniture_castle_divan.png")
add_entity_to_list("data/entities/props/furniture_castle_statue.xml","Castle Statue","props","data/props_gfx/furniture_castle_statue.png")
add_entity_to_list("data/entities/props/furniture_castle_table.xml","Castle Table","props","data/props_gfx/furniture_castle_table.png")
add_entity_to_list("data/entities/props/furniture_castle_wardrobe.xml","Castle Wardrobe","props","data/props_gfx/furniture_castle_wardrobe.png")
add_entity_to_list("data/entities/props/furniture_cryopod.xml","Cryopod","props","data/props_gfx/furniture_cryopod.png")
add_entity_to_list("data/entities/props/furniture_bed.xml","Bed","props","data/props_gfx/furniture_bed.png")
add_entity_to_list("data/entities/props/furniture_bunk.xml","Bunk Bed","props","data/props_gfx/furniture_bunk_bed.png")
add_entity_to_list("data/entities/props/furniture_dresser.xml","Dresser","props","data/props_gfx/furniture_dresser.png")
add_entity_to_list("data/entities/props/furniture_footlocker.xml","Footlocker","props","data/props_gfx/furniture_footlocker.png")
add_entity_to_list("data/entities/props/furniture_locker.xml","Locker","props","data/props_gfx/furniture_locker_frame.png")
add_entity_to_list("data/entities/props/furniture_rocking_chair.xml","Rocking Chair","props","data/props_gfx/furniture_rocking_chair.png")
add_entity_to_list("data/entities/props/furniture_stool.xml","Stool","props","data/props_gfx/furniture_stool.png")
add_entity_to_list("data/entities/props/furniture_table.xml","Table","props","data/props_gfx/furniture_table_middle.png")
add_entity_to_list("data/entities/props/furniture_wardrobe.xml","Wardrobe","props","data/props_gfx/furniture_wardrobe.png")
add_entity_to_list("data/entities/props/furniture_wood_chair.xml","Wood Chair","props","data/props_gfx/furniture_wood_chair.png")
add_entity_to_list("data/entities/props/furniture_wood_table.xml","Wood Table","props","data/props_gfx/furniture_wood_table.png")
add_entity_to_list("data/entities/props/furniture_tombstone_01.xml","Tombstone (1)","props","data/props_gfx/furniture_tombstone_01.png")
add_entity_to_list("data/entities/props/furniture_tombstone_02.xml","Tombstone (2)","props","data/props_gfx/furniture_tombstone_02.png")
add_entity_to_list("data/entities/props/furniture_tombstone_03.xml","Tombstone (3)","props","data/props_gfx/furniture_tombstone_03.png")
add_entity_to_list("data/entities/props/physics_barrel_burning.xml","Burning Barrel","props","data/props_gfx/barrel_burning.png")
add_entity_to_list("data/entities/props/physics_barrel_oil.xml","Oil Barrel","props","data/props_gfx/barrel_unstable.png")
add_entity_to_list("data/entities/props/physics_barrel_radioactive.xml","Toxic Barrel","props","data/props_gfx/barrel_radioactive.png")
add_entity_to_list("data/entities/props/physics_barrel_water.xml","Water Barrel","props","data/props_gfx/barrel_water.png")
add_entity_to_list("data/entities/props/physics_box_explosive.xml","Explosive Box","props","data/props_gfx/tnt.png")
add_entity_to_list("data/entities/props/physics_box_harmless_small.xml","Small Box","props","data/props_gfx/box_small.png")
add_entity_to_list("data/entities/props/physics_box_harmless.xml","Box","props","data/props_gfx/box.png")
add_entity_to_list("data/entities/props/physics_brewing_stand.xml","Whiskey Keg","props","data/props_gfx/brewing_stand.png")
add_entity_to_list("data/entities/props/physics_bone_01.xml","Bone (1)","props","data/props_gfx/bone_01.png")
add_entity_to_list("data/entities/props/physics_bone_02.xml","Bone (2)","props","data/props_gfx/bone_02.png")
add_entity_to_list("data/entities/props/physics_bone_03.xml","Bone (3)","props","data/props_gfx/bone_03.png")
add_entity_to_list("data/entities/props/physics_bone_04.xml","Bone (4)","props","data/props_gfx/bone_04.png")
add_entity_to_list("data/entities/props/physics_bone_05.xml","Bone (5)","props","data/props_gfx/bone_05.png")
add_entity_to_list("data/entities/props/physics_bone_06.xml","Bone (6)","props","data/props_gfx/bone_06.png")
add_entity_to_list("data/entities/props/physics_bottle_blue.xml","Blue Bottle","props","data/props_gfx/bottle_blue.png")
add_entity_to_list("data/entities/props/physics_bottle_green.xml","Green Bottle","props","data/props_gfx/bottle_green.png")
add_entity_to_list("data/entities/props/physics_bottle_red.xml","Red Bottle","props","data/props_gfx/bottle_red.png")
add_entity_to_list("data/entities/props/physics_bottle_yellow.xml","Yellow Bottle","props","data/props_gfx/bottle_yellow.png")
add_entity_to_list("data/entities/props/physics_candle_1.xml","Candle (1)","props","data/props_gfx/candle_1.png")
add_entity_to_list("data/entities/props/physics_candle_2.xml","Candle (2)","props","data/props_gfx/candle_2.png")
add_entity_to_list("data/entities/props/physics_candle_3.xml","Candle (3)","props","data/props_gfx/candle_3.png")
add_entity_to_list("data/entities/props/physics_skull_01.xml","Skull (1)","props","data/props_gfx/skull_01.png")
add_entity_to_list("data/entities/props/physics_skull_02.xml","Skull (2)","props","data/props_gfx/skull_02.png")
add_entity_to_list("data/entities/props/physics_skull_03.xml","Skull (3)","props","data/props_gfx/skull_03.png")
add_entity_to_list("data/entities/props/physics_stone_01.xml","Stone (1)","props","data/props_gfx/stone_01.png")
add_entity_to_list("data/entities/props/physics_stone_02.xml","Stone (2)","props","data/props_gfx/stone_02.png")
add_entity_to_list("data/entities/props/physics_stone_03.xml","Stone (3)","props","data/props_gfx/stone_03.png")
add_entity_to_list("data/entities/props/physics_stone_04.xml","Stone (4)","props","data/props_gfx/stone_04.png")
add_entity_to_list("data/entities/props/pumpkin_01.xml","Pumpkin (1)","props","data/props_gfx/pumpkin_01.png")
add_entity_to_list("data/entities/props/pumpkin_02.xml","Pumpkin (2)","props","data/props_gfx/pumpkin_02.png")
add_entity_to_list("data/entities/props/pumpkin_03.xml","Pumpkin (3)","props","data/props_gfx/pumpkin_03.png")
add_entity_to_list("data/entities/props/pumpkin_04.xml","Pumpkin (4)","props","data/props_gfx/pumpkin_04.png")




--wands
add_entity_to_list("data/entities/items/starting_wand.xml","starting wand","wands","data/items_gfx/handgun.png")
add_entity_to_list("data/entities/items/starting_bomb_wand.xml","starting bomb wand","wands","data/items_gfx/bomb_wand.png")
add_entity_to_list("data/entities/items/wands/wand_good/wand_good_1.xml","Wand of Swiftness","wands","data/items_gfx/wands/custom/good_01.png")
add_entity_to_list("data/entities/items/wands/wand_good/wand_good_2.xml","Wand of Destruction","wands","data/items_gfx/wands/custom/good_02.png")
add_entity_to_list("data/entities/items/wands/wand_good/wand_good_3.xml","Wand of Multitudes","wands","data/items_gfx/wands/custom/good_03.png")
add_entity_to_list("data/entities/items/wand_level_01.xml","Level 1 wand","wands","data/items_gfx/wands/wand_0018.png")
add_entity_to_list("data/entities/items/wand_level_01_better.xml","Level 1 wand (better)","wands","data/items_gfx/wands/wand_0015.png")
add_entity_to_list("data/entities/items/wand_level_02.xml","Level 2 wand","wands","data/items_gfx/wands/wand_0018.png")
add_entity_to_list("data/entities/items/wand_level_02_better.xml","Level 2 wand (better)","wands","data/items_gfx/wands/wand_0015.png")
add_entity_to_list("data/entities/items/wand_level_03.xml","Level 3 wand","wands","data/items_gfx/wands/wand_0018.png")
add_entity_to_list("data/entities/items/wand_level_03_better.xml","Level 3 wand (better)","wands","data/items_gfx/wands/wand_0015.png")
add_entity_to_list("data/entities/items/wand_level_04.xml","Level 4 wand","wands","data/items_gfx/wands/wand_0018.png")
add_entity_to_list("data/entities/items/wand_level_04_better.xml","Level 4 wand (better)","wands","data/items_gfx/wands/wand_0015.png")
add_entity_to_list("data/entities/items/wand_level_05.xml","Level 5 wand","wands","data/items_gfx/wands/wand_0018.png")
add_entity_to_list("data/entities/items/wand_level_05_better.xml","Level 5 wand (better)","wands","data/items_gfx/wands/wand_0015.png")
add_entity_to_list("data/entities/items/wand_level_06.xml","Level 6 wand","wands","data/items_gfx/wands/wand_0018.png")
add_entity_to_list("data/entities/items/wand_level_06_better.xml","Level 6 wand (better)","wands","data/items_gfx/wands/wand_0015.png")
add_entity_to_list("data/entities/items/wand_level_10.xml","Level 10 wand","wands","data/items_gfx/wands/wand_0040.png")
add_entity_to_list("data/entities/items/flute.xml","ocarina","wands","data/items_gfx/flute.png")
add_entity_to_list("data/entities/items/kantele.xml","kantele","wands","data/items_gfx/kantele.png")
add_entity_to_list("data/entities/items/wand_kiekurakeppi.xml","kiekurakeppi","wands","data/items_gfx/wands/custom/wood_01.png")
add_entity_to_list("data/entities/items/wand_leukaluu.xml","leukaluu","wands","data/items_gfx/wands/custom/leukaluu.png")
add_entity_to_list("data/entities/items/wand_ruusu.xml","ruusu","wands","data/items_gfx/wands/custom/plant_01.png")
add_entity_to_list("data/entities/items/wand_valtikka.xml","valtikka","wands","data/items_gfx/wands/custom/scepter_01.png")
add_entity_to_list("data/entities/items/wand_varpuluuta.xml","varpuluuta","wands","data/items_gfx/wands/custom/plant_02.png")
add_entity_to_list("data/entities/items/wand_vasta.xml","vasta","wands","data/items_gfx/wands/custom/vasta.png")
add_entity_to_list("data/entities/items/wand_vihta.xml","vihta","wands","data/items_gfx/wands/custom/vihta.png")
add_entity_to_list("data/entities/items/wands/experimental/experimental_wand_1.xml","experimental wand (conditionals)","wands","data/entities/items/wands/experimental/experimental_wand_1.png")
add_entity_to_list("data/entities/items/wands/experimental/experimental_wand_2.xml","experimental wand (glimmers)","wands","data/entities/items/wands/experimental/experimental_wand_2.png")
add_entity_to_list("data/entities/items/wands/experimental/experimental_wand_3.xml","experimental wand (machine gun)","wands","data/items_gfx/wands/custom/actual_wand_honest.png")
add_entity_to_list("data/entities/items/wands/experimental/experimental_wand_4.xml","Saha","wands","data/items_gfx/wands/custom/chainsaw.png")


--pickups
add_entity_to_list("data/entities/items/pickup/heart.xml","heart","pickups","data/items_gfx/heart_extrahp.png")
add_entity_to_list("data/entities/items/pickup/heart_better.xml","strong heart","pickups","data/items_gfx/heart_extrahp.png")
add_entity_to_list("data/entities/items/pickup/heart_evil.xml","cursed heart","pickups","data/items_gfx/heart_extrahp_evil.png")
add_entity_to_list("data/entities/items/pickup/heart_fullhp.xml","HP restore","pickups","data/items_gfx/heart.png")
add_entity_to_list("data/entities/items/pickup/heart_fullhp_temple.xml","HP restore and increase","pickups","data/items_gfx/heart.png")

add_entity_to_list("data/entities/items/pickup/spell_refresh.xml","spell refresher","pickups","data/items_gfx/spell_refresh.png")
add_entity_to_list("data/entities/items/pickup/utility_box.xml","utility box","pickups","data/items_gfx/utility_box.png")
add_entity_to_list("data/entities/items/pickup/chest_random.xml","treasure chest","pickups","data/buildings_gfx/chest_random.png")
add_entity_to_list("data/entities/items/pickup/chest_random_super.xml","great treasure chest","pickups","data/buildings_gfx/chest_random_super.png")

add_entity_to_list("data/entities/buildings/chest_light.xml","choral chest","pickups","data/buildings_gfx/chest_light.png")
add_entity_to_list("data/entities/buildings/chest_dark.xml","dark chest","pickups","data/buildings_gfx/chest_dark.png")

add_entity_to_list("data/entities/items/pickup/essence_air.xml","essence of air","pickups","data/items_gfx/essences/essence_air.png")
add_entity_to_list("data/entities/items/pickup/essence_fire.xml","essence of fire","pickups","data/items_gfx/essences/essence_fire.png")
add_entity_to_list("data/entities/items/pickup/essence_laser.xml","essence of earth","pickups","data/items_gfx/essences/essence_laser.png")
add_entity_to_list("data/entities/items/pickup/essence_water.xml","essence of water","pickups","data/items_gfx/essences/essence_water.png")
add_entity_to_list("data/entities/items/pickup/essence_alcohol.xml","essence of spirits","pickups","data/items_gfx/essences/essence_alcohol.png")

add_entity_to_list("data/entities/items/pickup/greed_curse.xml","curse of greed","pickups","data/items_gfx/greed_curse.png")




--items
add_entity_to_list("data/entities/items/pickup/brimstone.xml","kiuaskivi (fire stone)","items","data/items_gfx/brimstone.png")
add_entity_to_list("data/entities/items/pickup/thunderstone.xml","ukkoskivi (thunder stone)","items","data/items_gfx/thunderstone.png")
add_entity_to_list("data/entities/items/pickup/waterstone.xml","vuoksikivi (water stone)","items","data/items_gfx/waterstone.png")
add_entity_to_list("data/entities/items/pickup/stonestone.xml","tannerkivi (earth stone)","items","data/items_gfx/stonestone.png")
add_entity_to_list("data/entities/items/pickup/poopstone.xml","kakkakikkare (poop stone)","items","data/items_gfx/kakke.png")
add_entity_to_list("data/entities/items/pickup/sun/sunseed.xml","auringonsiemen (sun seed)","items","data/items_gfx/sunseed.png")

add_entity_to_list("data/entities/animals/boss_alchemist/key.xml.xml","crystal key","items","data/items_gfx/key.png")

add_entity_to_list("data/entities/items/pickup/broken_wand.xml","broken wand","items","data/items_gfx/broken_wand.png")

add_entity_to_list("data/entities/items/pickup/summon_portal_broken.xml","broken spell","items","data/items_gfx/broken_spell.png")

add_entity_to_list("data/entities/items/pickup/evil_eye.xml","paha silmä (evil eye)","items","data/items_gfx/evil_eye.png")

add_entity_to_list("data/entities/items/pickup/safe_haven.xml","kammi (save haven)","items","data/items_gfx/safe_haven.png")

add_entity_to_list("data/entities/items/pickup/moon.xml","kuu (moon)","items","data/items_gfx/moon.png")

add_entity_to_list("data/entities/items/pickup/physics_gold_orb.xml","shiny orb","items","data/items_gfx/orb.png")
add_entity_to_list("data/entities/items/pickup/physics_gold_orb_greed.xml","cruel orb","items","data/items_gfx/orb_greed.png")

add_entity_to_list("data/entities/items/pickup/physics_die.xml","chaos die","items","data/items_gfx/in_hand/die.png")
add_entity_to_list("data/entities/items/pickup/physics_greed_die.xml","greed die","items","data/items_gfx/in_hand/greed_die.png")

add_entity_to_list("data/entities/items/pickup/gourd.xml","refreshing gourd","items","data/items_gfx/gourd.png")

add_entity_to_list("data/entities/items/pickup/beamstone.xml","sädekvi (beamstone)","items","data/items_gfx/in_hand/beamstone.png")

add_entity_to_list("data/entities/items/pickup/musicstone.xml","kuulokivi (music stone)","items","data/items_gfx/in_hand/musicstone.png")

add_entity_to_list("data/entities/items/pickup/wandstone.xml","sauvan ydin (wand stone)","items","data/items_gfx/wandstone.png")

add_entity_to_list("data/entities/items/pickup/runestones/runestone_slow.xml","runestone of weight","items","data/items_gfx/runestones/runestone_slow.png")
add_entity_to_list("data/entities/items/pickup/runestones/runestone_disc.xml","runestone of edges","items","data/items_gfx/runestones/runestone_disc.png")
add_entity_to_list("data/entities/items/pickup/runestones/runestone_fireball.xml","runestone of fire","items","data/items_gfx/runestones/runestone_fireball.png")
add_entity_to_list("data/entities/items/pickup/runestones/runestone_laser.xml","runestone of light","items","data/items_gfx/runestones/runestone_laser.png")
add_entity_to_list("data/entities/items/pickup/runestones/runestone_lava.xml","runestone of lava","items","data/items_gfx/runestones/runestone_lava.png")
add_entity_to_list("data/entities/items/pickup/runestones/runestone_metal.xml","runestone of metal","items","data/items_gfx/runestones/runestone_metal.png")
add_entity_to_list("data/entities/items/pickup/runestones/runestone_null.xml","runestone of emptiness","items","data/items_gfx/runestones/runestone_null.png")

add_entity_to_list("data/entities/items/pickup/potion_empty.xml","empty potion","items","data/items_gfx/potion.png")
add_entity_to_list("data/entities/items/pickup/potion.xml","potion","items","data/items_gfx/potion.png")
add_entity_to_list("data/entities/items/pickup/potion_starting.xml","starting potion","items","data/items_gfx/potion.png")
add_entity_to_list("data/entities/items/pickup/potion_aggressive.xml","alchemist Hiisi potion","items","data/items_gfx/potion_alchemist.png")
add_entity_to_list("data/entities/items/pickup/jar.xml","jar","items","data/items_gfx/jar.png")
add_entity_to_list("data/entities/items/pickup/jar_of_urine.xml","jarate","items","data/items_gfx/jar.png")
add_entity_to_list("data/entities/items/pickup/powder_stash.xml","powder pouch","items","data/items_gfx/material_pouch.png")


add_entity_to_list("data/entities/items/books/book_00.xml","Emerald Tablet - Volume I","items","data/items_gfx/emerald_tablet.png")
add_entity_to_list("data/entities/items/books/book_01.xml","Emerald Tablet of Toth","items","data/items_gfx/emerald_tablet.png")
add_entity_to_list("data/entities/items/books/book_02.xml","Emerald Tablet - Volume II","items","data/items_gfx/emerald_tablet.png")
add_entity_to_list("data/entities/items/books/book_03.xml","Emerald Tablet - Volume III","items","data/items_gfx/emerald_tablet.png")
add_entity_to_list("data/entities/items/books/book_04.xml","Emerald Tablet - Volume IV","items","data/items_gfx/emerald_tablet.png")
add_entity_to_list("data/entities/items/books/book_05.xml","Emerald Tablet - Volume V","items","data/items_gfx/emerald_tablet.png")
add_entity_to_list("data/entities/items/books/book_06.xml","Emerald Tablet - Volume VI","items","data/items_gfx/emerald_tablet.png")
add_entity_to_list("data/entities/items/books/book_07.xml","Emerald Tablet - Volume VII","items","data/items_gfx/emerald_tablet.png")
add_entity_to_list("data/entities/items/books/book_08.xml","Emerald Tablet - Volume VIII","items","data/items_gfx/emerald_tablet.png")
add_entity_to_list("data/entities/items/books/book_09.xml","Emerald Tablet - Volume IX","items","data/items_gfx/emerald_tablet.png")
add_entity_to_list("data/entities/items/books/book_10.xml","Emerald Tablet - Volume X","items","data/items_gfx/emerald_tablet.png")
add_entity_to_list("data/entities/items/books/book_all_spells.xml","Map of Gnosis","items","data/items_gfx/laboratory_tablet.png")
add_entity_to_list("data/entities/items/books/book_barren.xml","Adept's Note","items","data/items_gfx/book.png")
add_entity_to_list("data/entities/items/books/book_bunker.xml","Alchemist's Note","items","data/items_gfx/book.png")
add_entity_to_list("data/entities/items/books/book_corpse.xml","Tabula Smaragdina","items","data/items_gfx/laboratory_tablet.png")
add_entity_to_list("data/entities/items/books/book_diamond.xml","Book of the Jewel","items","data/items_gfx/book.png")
add_entity_to_list("data/entities/items/books/book_essences.xml","Tome of Essences","items","data/items_gfx/book.png")
add_entity_to_list("data/entities/items/books/book_hint.xml","Book of Guidance","items","data/items_gfx/book.png")
add_entity_to_list("data/entities/items/books/book_mestari.xml","A Cunning Contraption","items","data/items_gfx/book.png")
add_entity_to_list("data/entities/items/books/book_moon.xml","Book of Celestial Bodies","items","data/items_gfx/book.png")
add_entity_to_list("data/entities/items/books/book_music_a.xml","Alchemist's Notebook","items","data/items_gfx/book.png")
add_entity_to_list("data/entities/items/books/book_music_b.xml","Research Notes","items","data/items_gfx/book.png")
add_entity_to_list("data/entities/items/books/book_music_c.xml","Book of the key","items","data/items_gfx/book.png")
add_entity_to_list("data/entities/items/books/book_robot.xml","Musings of an Adventurer","items","data/items_gfx/book.png")
add_entity_to_list("data/entities/items/books/book_s_a.xml","Notes on Grand Alchemy (1)","items","data/items_gfx/book_s.png")
add_entity_to_list("data/entities/items/books/book_s_b.xml","Notes on Grand Alchemy (2)","items","data/items_gfx/book_s.png")
add_entity_to_list("data/entities/items/books/book_s_c.xml","Notes on Grand Alchemy (3)","items","data/items_gfx/book_s.png")
add_entity_to_list("data/entities/items/books/book_s_d.xml","Notes on Grand Alchemy (4)","items","data/items_gfx/book_s.png")
add_entity_to_list("data/entities/items/books/book_s_e.xml","Notes on Grand Alchemy (5)","items","data/items_gfx/book_s.png")
add_entity_to_list("data/entities/items/books/book_tree.xml","Secretorum Hermetis","items","data/items_gfx/emerald_tablet.png")



--enemies
add_entity_to_list("data/entities/animals/acidshooter_weak.xml","Hiekko Happonuljaska (Weak Acid spitter)","enemies","data/ui_gfx/animal_icons/acidshooter_weak.png")
add_entity_to_list("data/entities/animals/acidshooter.xml","Happonuljaska (Acid spitter)","enemies","data/ui_gfx/animal_icons/acidshooter.png")
add_entity_to_list("data/entities/animals/alchemist.xml","Puistokemisi (Alchemist hiisi)","enemies","data/ui_gfx/animal_icons/alchemist.png")
add_entity_to_list("data/entities/animals/ant.xml","Murkku (Ant)","enemies","data/ui_gfx/animal_icons/ant.png")
add_entity_to_list("data/entities/animals/assassin.xml","Salamurhaajarobotti (Assasin)","enemies","data/ui_gfx/animal_icons/assassin.png")
add_entity_to_list("data/entities/animals/barfer.xml","Turvonnu velho (Bloated Wizard)","enemies","data/ui_gfx/animal_icons/barfer.png")
add_entity_to_list("data/entities/animals/basebot_hidden.xml","Vakoilija (Spy)","enemies","data/ui_gfx/animal_icons/basebot_hidden.png")
add_entity_to_list("data/entities/animals/basebot_neutralizer.xml","Pysäyttäjä (Stopper)","enemies","data/ui_gfx/animal_icons/basebot_neutralizer.png")
add_entity_to_list("data/entities/animals/basebot_sentry.xml","Tarkkailija (Observer)","enemies","data/ui_gfx/animal_icons/basebot_sentry.png")
add_entity_to_list("data/entities/animals/basebot_soldier.xml","Teloittaja (Executioner)","enemies","data/ui_gfx/animal_icons/basebot_soldier.png")
add_entity_to_list("data/entities/animals/bat.xml","Lepakko (Bat)","enemies","data/ui_gfx/animal_icons/bat.png")
add_entity_to_list("data/entities/animals/berserkspirit.xml","Viha-Aave (Anger Spirit)","enemies","data/ui_gfx/animal_icons/berserkspirit.png")
add_entity_to_list("data/entities/animals/bigbat.xml","Suurlepakko (Large Bat)","enemies","data/ui_gfx/animal_icons/bigbat.png")
add_entity_to_list("data/entities/animals/bigfirebug.xml","Suurtulikärpänen (Greater firefly)","enemies","data/ui_gfx/animal_icons/bigfirebug.png")
add_entity_to_list("data/entities/animals/bigzombie.xml","Mätänevä ruumis (Rotting Corpse)","enemies","data/ui_gfx/animal_icons/bigzombie.png")
add_entity_to_list("data/entities/animals/blob.xml","Kiukkumöykky (Angry Blob)","enemies","data/ui_gfx/animal_icons/blob.png")
add_entity_to_list("data/entities/animals/bloodcrystal_physics.xml","Verikristalli (Blood Crystal)","enemies","data/ui_gfx/animal_icons/bloodcrystal_physics.png")
add_entity_to_list("data/entities/animals/bloom.xml","Puska (Bloom)","enemies","data/ui_gfx/animal_icons/bloom.png")
add_entity_to_list("data/entities/animals/chest_leggy.xml","Jalkamatkatavara (Leggy Mimic)","enemies","data/ui_gfx/animal_icons/chest_leggy.png")
add_entity_to_list("data/entities/animals/chest_mimic.xml","Matkija (Mimic)","enemies","data/ui_gfx/animal_icons/chest_mimic.png")
add_entity_to_list("data/entities/animals/confusespirit.xml","Utu-Aave (Fog Spirit)","enemies","data/ui_gfx/animal_icons/confusespirit.png")
add_entity_to_list("data/entities/animals/coward.xml","Raukka (Coward)","enemies","data/ui_gfx/animal_icons/coward.png")
add_entity_to_list("data/entities/animals/crystal_physics.xml","Kirottu kristalli (Cursed Crystal)","enemies","data/ui_gfx/animal_icons/crystal_physics.png")
--add_entity_to_list("data/entities/animals/darkghost.xml","? (?)","enemies") --unused enemy
add_entity_to_list("data/entities/animals/deer.xml","Nelikoipi (Deer)","enemies","data/ui_gfx/animal_icons/deer.png")
--add_entity_to_list("data/entities/animals/drone.xml","Lennokki (Drone)","enemies") --unused enemy
add_entity_to_list("data/entities/animals/drone_lasership.xml","Jättilaser-lennokki (Giant Laser-Drone)","enemies","data/ui_gfx/animal_icons/drone_lasership.png")
add_entity_to_list("data/entities/animals/drone_physics.xml","Lennokki (Drone)","enemies","data/ui_gfx/animal_icons/drone_physics.png")
add_entity_to_list("data/entities/animals/drone_shield.xml","Turvalennokki (Safety Drone)","enemies","data/ui_gfx/animal_icons/drone_shield.png")
add_entity_to_list("data/entities/animals/duck.xml","Ankka (Duck)","enemies","data/ui_gfx/animal_icons/duck.png")
add_entity_to_list("data/entities/animals/eel.xml","Nahkiainen (Lamprey)","enemies","data/ui_gfx/animal_icons/eel.png")
add_entity_to_list("data/entities/animals/elk.xml","Poro (Reindeer)","enemies","data/ui_gfx/animal_icons/elk.png")
add_entity_to_list("data/entities/animals/enlightened_alchemist.xml","Valaistunut alkemisti (enlightened alchemist)","enemies","data/ui_gfx/animal_icons/enlightened_alchemist.png")
add_entity_to_list("data/entities/animals/ethereal_being.xml","Olematon (Non-existent)","enemies","data/ui_gfx/animal_icons/ethereal_being.png")
add_entity_to_list("data/entities/animals/failed_alchemist.xml","Kadotettu alkemisti (Damned Alchemist)","enemies","data/ui_gfx/animal_icons/failed_alchemist.png")
add_entity_to_list("data/entities/animals/failed_alchemist_b.xml","Epäalkemisti (Non-alchemist)","enemies","data/ui_gfx/animal_icons/failed_alchemist_b.png")
add_entity_to_list("data/entities/animals/firebug.xml","Pikkutulikärpänen (Firefly)","enemies","data/ui_gfx/animal_icons/firebug.png")
add_entity_to_list("data/entities/animals/firemage.xml","Eldari (Hellfire Mage)","enemies","data/ui_gfx/animal_icons/firemage.png")
add_entity_to_list("data/entities/animals/firemage_weak.xml","Stendari (Fire Mage)","enemies","data/ui_gfx/animal_icons/firemage_weak.png")
add_entity_to_list("data/entities/animals/fireskull.xml","Liekkiö (Fire Spirit)","enemies","data/ui_gfx/animal_icons/fireskull.png")
add_entity_to_list("data/entities/animals/fireskull_weak.xml","Liekkiö (Fire Spirit) (weak)","enemies","data/ui_gfx/animal_icons/fireskull.png")
add_entity_to_list("data/entities/animals/fish.xml","Eväkäs (Fish)","enemies","data/ui_gfx/animal_icons/fish.png")
add_entity_to_list("data/entities/animals/fish_large.xml","Suureväkäs (Large fish)","enemies","data/ui_gfx/animal_icons/fish_large.png")
add_entity_to_list("data/entities/animals/flamer.xml","Liekkari (Flamer)","enemies","data/ui_gfx/animal_icons/flamer.png")
add_entity_to_list("data/entities/animals/fly.xml","Amppari (Wasp)","enemies","data/ui_gfx/animal_icons/fly.png")

add_entity_to_list("data/entities/animals/frog.xml","Konna (Toad)","enemies","data/ui_gfx/animal_icons/frog.png")
add_entity_to_list("data/entities/animals/frog_big.xml","Jättikonna (Big Toad)","enemies","data/ui_gfx/animal_icons/frog_big.png")
add_entity_to_list("data/entities/animals/fungus.xml","Laahustussieni (Shuffling Fungus)","enemies","data/ui_gfx/animal_icons/fungus.png")
add_entity_to_list("data/entities/animals/fungus_big.xml","Nuijamalikka (Club-foot)","enemies","data/ui_gfx/animal_icons/fungus_big.png")
add_entity_to_list("data/entities/animals/fungus_giga.xml","Huhtasieni (Pollen Morel)","enemies","data/ui_gfx/animal_icons/fungus_giga.png")
add_entity_to_list("data/entities/animals/fungus_tiny.xml","Myrkkynääpikkä (Funeral Bell)","enemies","data/enemies_gfx/fungus_tiny.png")
add_entity_to_list("data/entities/animals/gazer.xml","Helvetinkatse (Hell Gazer)","enemies","data/ui_gfx/animal_icons/gazer.png")
add_entity_to_list("data/entities/animals/ghost.xml","Houre (Delirium)","enemies","data/ui_gfx/animal_icons/ghost.png")
add_entity_to_list("data/entities/animals/ghoul.xml","Sylkyri (Spitter)","enemies","data/ui_gfx/animal_icons/ghoul.png")
add_entity_to_list("data/entities/animals/giant.xml","Hiidenkivi (Rock Giant)","enemies","data/ui_gfx/animal_icons/giant.png")
add_entity_to_list("data/entities/animals/giantshooter.xml","Äitinuljaska (Mother Slime)","enemies","data/ui_gfx/animal_icons/giantshooter.png")
add_entity_to_list("data/entities/animals/giantshooter_weak.xml","Heikko äitinuljaska (Weak Mother Slime)","enemies","data/ui_gfx/animal_icons/giantshooter_weak.png")
add_entity_to_list("data/entities/animals/goblin_bomb.xml","Sähikäismenninkäinen (Firecracker Goblin)","enemies","data/ui_gfx/animal_icons/goblin_bomb.png")
add_entity_to_list("data/entities/animals/healerdrone_physics.xml","Korjauslennokki (Repair Drone)","enemies","data/ui_gfx/animal_icons/healerdrone_physics.png")
add_entity_to_list("data/entities/animals/icemage.xml","Pakkasukko (Old Man Winter)","enemies","data/ui_gfx/animal_icons/icemage.png")
add_entity_to_list("data/entities/animals/icer.xml","Jäähdytyslaite (Icer)","enemies","data/ui_gfx/animal_icons/icer.png")
add_entity_to_list("data/entities/animals/iceskull.xml","Jäätiö (Ice Spirit)","enemies","data/ui_gfx/animal_icons/iceskull.png")
add_entity_to_list("data/entities/animals/lasershooter.xml","Mulkkio (Gazer)","enemies","data/ui_gfx/animal_icons/lasershooter.png")
add_entity_to_list("data/entities/animals/longleg.xml","Hämis","enemies","data/ui_gfx/animal_icons/longleg.png")
add_entity_to_list("data/entities/animals/lurker.xml","Varjokupla (Shadow Bubble)","enemies","data/ui_gfx/animal_icons/lurker.png")
add_entity_to_list("data/entities/animals/maggot.xml","Toukka (Maggot)","enemies","data/ui_gfx/animal_icons/maggot.png")
add_entity_to_list("data/entities/animals/meatmaggot.xml","Mätäryömijä (Putrid Crawler)","enemies","data/ui_gfx/animal_icons/meatmaggot.png")
add_entity_to_list("data/entities/animals/mimic_potion.xml","Henkevä potu (Potion Mimic)","enemies","data/ui_gfx/animal_icons/mimic_potion.png")
add_entity_to_list("data/entities/animals/miner.xml","Tappurahiisi (Miner Hiisi)","enemies","data/ui_gfx/animal_icons/miner.png")
add_entity_to_list("data/entities/animals/miner_chef.xml","Kokkihiisi (Hiisi Chef)","enemies","data/ui_gfx/animal_icons/miner_chef.png")
add_entity_to_list("data/entities/animals/miner_fire.xml","Tulihiisi (Fire Hiisi)","enemies","data/ui_gfx/animal_icons/miner_fire.png")
add_entity_to_list("data/entities/animals/miner_hell.xml","Hornantappurahiisi (Hell Miner Hiisi)","enemies","data/ui_gfx/animal_icons/miner_hell.png")
add_entity_to_list("data/entities/animals/miner_santa.xml","Jouluhiisi (Christmas Hiisi)","enemies","data/ui_gfx/animal_icons/miner_santa.png")
add_entity_to_list("data/entities/animals/miner_weak.xml","Tappurahiisiläinen (Weak Hiisi miner)","enemies","data/ui_gfx/animal_icons/miner_santa.png")
add_entity_to_list("data/entities/animals/miniblob.xml","Möykky (Blob)","enemies","data/ui_gfx/animal_icons/miniblob.png")
add_entity_to_list("data/entities/animals/missilecrab.xml","Heinäsirkka (Cricket)","enemies","data/ui_gfx/animal_icons/missilecrab.png")
add_entity_to_list("data/entities/animals/monk.xml","Munkki (Monk)","enemies","data/ui_gfx/animal_icons/monk.png")
add_entity_to_list("data/entities/animals/necrobot.xml","Tuonelankone (Necrobot)","enemies","data/ui_gfx/animal_icons/necrobot.png")
add_entity_to_list("data/entities/animals/necrobot_super.xml","Marraskone (Super Necrobot)","enemies","data/ui_gfx/animal_icons/necrobot_super.png")
add_entity_to_list("data/entities/animals/necromancer.xml","Hahmonvaihtaja (Shapechanger)","enemies","data/ui_gfx/animal_icons/necromancer.png")
add_entity_to_list("data/entities/animals/necromancer_shop.xml","Stevari (Guard)","enemies","data/ui_gfx/animal_icons/necromancer_shop.png")
add_entity_to_list("data/entities/animals/necromancer_super.xml","Skoude (Cop)","enemies","data/ui_gfx/animal_icons/necromancer_super.png")
add_entity_to_list("data/entities/animals/pebble_physics.xml","Lohkare (Rock Spirit)","enemies","data/ui_gfx/animal_icons/pebble_physics.png")
add_entity_to_list("data/entities/animals/phantom_a.xml","(Spiraalikalma (Spiral Phantom)","enemies","data/ui_gfx/animal_icons/phantom_a.png")
add_entity_to_list("data/entities/animals/phantom_b.xml","Kiukkukalma (Angry Phantom)","enemies","data/ui_gfx/animal_icons/phantom_b.png")
add_entity_to_list("data/entities/animals/playerghost.xml","Kummitus (Ghost)","enemies","data/ui_gfx/animal_icons/playerghost.png")
add_entity_to_list("data/entities/animals/rat.xml","Rotta (Rat)","enemies","data/ui_gfx/animal_icons/rat.png")
add_entity_to_list("data/entities/animals/roboguard.xml","Robottikyttä (Robo-Cop)","enemies","data/ui_gfx/animal_icons/roboguard.png")
add_entity_to_list("data/entities/animals/roboguard_big.xml","Kyrmyniska (Hunchback)","enemies","data/ui_gfx/animal_icons/roboguard_big.png")
add_entity_to_list("data/entities/animals/scavenger_clusterbomb.xml","Isohiisi (Hiisi Bomber)","enemies","data/ui_gfx/animal_icons/scavenger_clusterbomb.png")
add_entity_to_list("data/entities/animals/scavenger_glue.xml","Liimahiisi (Glue Hiisi)","enemies","data/ui_gfx/animal_icons/scavenger_glue.png")
add_entity_to_list("data/entities/animals/scavenger_grenade.xml","Kranuhiisi (Hiisi Grenadier)","enemies","data/ui_gfx/animal_icons/scavenger_grenade.png")
add_entity_to_list("data/entities/animals/scavenger_heal.xml","Parantajahiisi (Hiisi Healer)","enemies","data/ui_gfx/animal_icons/scavenger_heal.png")
add_entity_to_list("data/entities/animals/scavenger_invis.xml","Häivehiisi (Stealth Hiisi)","enemies","data/ui_gfx/animal_icons/scavenger_invis.png")
add_entity_to_list("data/entities/animals/scavenger_leader.xml","Toimari (Hiisi Leader)","enemies","data/ui_gfx/animal_icons/scavenger_leader.png")
add_entity_to_list("data/entities/animals/scavenger_mine.xml","Miinankylväjä (Hiisi Mine Thrower)","enemies","data/ui_gfx/animal_icons/scavenger_mine.png")
add_entity_to_list("data/entities/animals/scavenger_poison.xml","Myrkkyhiisi (Hiisi Poisoner)","enemies","data/ui_gfx/animal_icons/scavenger_poison.png")
add_entity_to_list("data/entities/animals/scavenger_shield.xml","Kilpihiisi (Shield Hiisi)","enemies","data/ui_gfx/animal_icons/scavenger_shield.png")
add_entity_to_list("data/entities/animals/scavenger_smg.xml","Rynkkyhiisi (Hiisi Gunner)","enemies","data/ui_gfx/animal_icons/scavenger_smg.png")
add_entity_to_list("data/entities/animals/scorpion.xml","Skorpioni (Scorpion)","enemies","data/ui_gfx/animal_icons/scorpion.png")
add_entity_to_list("data/entities/animals/scorpion_watchtower.xml","Skorpioni (Scorpion) (watchtower)","enemies","data/ui_gfx/animal_icons/scorpion.png")
add_entity_to_list("data/entities/animals/shaman.xml","Märkiäinen (Swampling)","enemies","data/ui_gfx/animal_icons/shaman.png")
add_entity_to_list("data/entities/animals/sheep.xml","Lammas (Sheep)","enemies","data/ui_gfx/animal_icons/sheep.png")
add_entity_to_list("data/entities/animals/sheep_bat.xml","Lentolammas (Flying Sheep)","enemies","data/ui_gfx/animal_icons/sheep_bat.png")
add_entity_to_list("data/entities/animals/sheep_fly.xml","Suhiseva lammas (Buzzing sheep)","enemies","data/ui_gfx/animal_icons/sheep_fly.png")
add_entity_to_list("data/entities/animals/shooterflower.xml","Plasmakukka (Plasma Flower)","enemies","data/ui_gfx/animal_icons/shooterflower.png")
add_entity_to_list("data/entities/animals/shotgunner.xml","Haulikkohiisi (Shotgun Hiisi)","enemies","data/ui_gfx/animal_icons/shotgunner.png")
add_entity_to_list("data/entities/animals/shotgunner_hell.xml","Hornahiisi (Hell Shotgun Hiisi)","enemies","data/ui_gfx/animal_icons/shotgunner_hell.png")
add_entity_to_list("data/entities/animals/shotgunner_weak.xml","Heikko haulikkohiisi (Weak shotgun Hiisi)","enemies","data/ui_gfx/animal_icons/shotgunner_weak.png")
add_entity_to_list("data/entities/animals/skullfly.xml","Kallokärpänen (Skull Fly)","enemies","data/ui_gfx/animal_icons/skullfly.png")
add_entity_to_list("data/entities/animals/skullrat.xml","Kallorotta (Skull Rat)","enemies","data/ui_gfx/animal_icons/skullrat.png")
add_entity_to_list("data/entities/animals/skycrystal_physics.xml","Taivaskristalli (Celestial Crystal)","enemies","data/ui_gfx/animal_icons/skycrystal_physics.png")
add_entity_to_list("data/entities/animals/skygazer.xml","Taivaankatse (Sky Gazer)","enemies","data/ui_gfx/animal_icons/skygazer.png")
add_entity_to_list("data/entities/animals/slimeshooter.xml","limanuljaska (Toxic Slime)","enemies","data/ui_gfx/animal_icons/slimeshooter.png")
add_entity_to_list("data/entities/animals/slimeshooter_weak.xml","Heikko limanuljaska (Weak Toxic Slime)","enemies","data/ui_gfx/animal_icons/slimeshooter_weak.png")
add_entity_to_list("data/entities/animals/slimespirit.xml","Neva-Aave (Bog Spirit)","enemies","data/ui_gfx/animal_icons/slimespirit.png")
add_entity_to_list("data/entities/animals/sniper.xml","Snipuhiisi (Hiisi Sniper)","enemies","data/ui_gfx/animal_icons/sniper.png")
add_entity_to_list("data/entities/animals/sniper_hell.xml","Hornasnipuhiisi (Hiisi Hell Sniper)","enemies","data/ui_gfx/animal_icons/sniper_hell.png")
add_entity_to_list("data/entities/animals/spearbot.xml","Peitsivartija (Lance Sentry)","enemies","data/ui_gfx/animal_icons/spearbot.png")
add_entity_to_list("data/entities/animals/spitmonster.xml","Helvetin sylkijä (Hell Spitter)","enemies","data/ui_gfx/animal_icons/spitmonster.png")
add_entity_to_list("data/entities/animals/statue.xml","Patsas (Statue)","enemies","data/ui_gfx/animal_icons/statue.png")
add_entity_to_list("data/entities/animals/statue_physics.xml","Hohtonaamio (Glowing Mask)","enemies","data/ui_gfx/animal_icons/statue_physics.png")
add_entity_to_list("data/entities/animals/tank.xml","KK-Tankki","enemies","data/ui_gfx/animal_icons/tank.png")
add_entity_to_list("data/entities/animals/tank_rocket.xml","IT-Tankki","enemies","data/ui_gfx/animal_icons/tank_rocket.png")
add_entity_to_list("data/entities/animals/tank_super.xml","Laser-Tankki","enemies","data/ui_gfx/animal_icons/tank_super.png")
add_entity_to_list("data/entities/animals/tentacler.xml","Turso (Tentacler)","enemies","data/ui_gfx/animal_icons/tentacler.png")
add_entity_to_list("data/entities/animals/tentacler_small.xml","Pikkuturso (Small Tentacler)","enemies","data/ui_gfx/animal_icons/tentacler_small.png")
add_entity_to_list("data/entities/animals/thundermage.xml","Ukko (Thunder Mage)","enemies","data/ui_gfx/animal_icons/thundermage.png")
add_entity_to_list("data/entities/animals/thundermage_big.xml","Suur-Ukko (Great Thunder Mage)","enemies","data/ui_gfx/animal_icons/thundermage_big.png")
add_entity_to_list("data/entities/animals/thunderskull.xml","Sähkiö (Thunder Spirit)","enemies","data/ui_gfx/animal_icons/thunderskull.png")
add_entity_to_list("data/entities/animals/turret_left.xml","Torjuntalaite (Turret) (left)","enemies","data/ui_gfx/animal_icons/turret_left.png")
add_entity_to_list("data/entities/animals/turret_right.xml","Torjuntalaite (Turret) (right)","enemies","data/ui_gfx/animal_icons/turret_right.png")
add_entity_to_list("data/entities/animals/ultimate_killer.xml","Kauhuhirviö (Horror Monster)","enemies","data/ui_gfx/animal_icons/ultimate_killer.png")
add_entity_to_list("data/entities/animals/wand_ghost.xml","Taikasauva (Magic Wand)","enemies","data/ui_gfx/animal_icons/wand_ghost.png")
add_entity_to_list("data/entities/animals/weakspirit.xml","Kaamo-Aave (Depression Spirit)","enemies","data/ui_gfx/animal_icons/weakspirit.png")
add_entity_to_list("data/entities/animals/wizard_dark.xml","Sokaisunmestari (Master of Blinding)","enemies","data/ui_gfx/animal_icons/wizard_dark.png")
add_entity_to_list("data/entities/animals/wizard_hearty.xml","Haavoittajamestari (Master of Wounding)","enemies","data/ui_gfx/animal_icons/wizard_hearty.png")
add_entity_to_list("data/entities/animals/wizard_homing.xml","Kohdennusmestari (Master of Homing)","enemies","data/ui_gfx/animal_icons/wizard_homing.png")
add_entity_to_list("data/entities/animals/wizard_neutral.xml","Maadoittajamestari (Master of Grounding)","enemies","data/ui_gfx/animal_icons/wizard_neutral.png")
add_entity_to_list("data/entities/animals/wizard_poly.xml","Muodonmuutosmestari (Master of Polymorphing)","enemies","data/ui_gfx/animal_icons/wizard_poly.png")
add_entity_to_list("data/entities/animals/wizard_returner.xml","Palauttajamestari (Master of Returning)","enemies","data/ui_gfx/animal_icons/wizard_returner.png")
add_entity_to_list("data/entities/animals/wizard_swapper.xml","Vaihdosmestari (Master of Exchanging)","enemies","data/ui_gfx/animal_icons/wizard_swapper.png")
add_entity_to_list("data/entities/animals/wizard_tele.xml","Siirtäjämestari (Master of Teleportation)","enemies","data/ui_gfx/animal_icons/wizard_tele.png")
add_entity_to_list("data/entities/animals/wizard_twitchy.xml","Sätkymestari (Master of Twitching)","enemies","data/ui_gfx/animal_icons/wizard_twitchy.png")
add_entity_to_list("data/entities/animals/wizard_weaken.xml","Turvattomuusmestari (Master of Vulnerability)","enemies","data/ui_gfx/animal_icons/wizard_weaken.png")
add_entity_to_list("data/entities/animals/wolf.xml","Susi (Wolf)","enemies","data/ui_gfx/animal_icons/wolf.png")
add_entity_to_list("data/entities/animals/worm.xml","Mato (Worm)","enemies","data/ui_gfx/animal_icons/worm.png")
add_entity_to_list("data/entities/animals/worm_big.xml","Jättimato (Giant worm)","enemies","data/ui_gfx/animal_icons/worm_big.png")
add_entity_to_list("data/entities/animals/worm_end.xml","Helvetinmato (Hell Worm)","enemies","data/ui_gfx/animal_icons/worm_end.png")
add_entity_to_list("data/entities/animals/worm_skull.xml","Kalmamato (Death Worm)","enemies","data/ui_gfx/animal_icons/worm_skull.png")
add_entity_to_list("data/entities/animals/worm_tiny.xml","Pikkumato (small worm)","enemies","data/ui_gfx/animal_icons/worm_tiny.png")
add_entity_to_list("data/entities/animals/wraith.xml","Hyypiö (Creep)","enemies","data/ui_gfx/animal_icons/wraith.png")
add_entity_to_list("data/entities/animals/wraith_glowing.xml","Hohtava hyypiö (Glowing Creep)","enemies","data/ui_gfx/animal_icons/wraith_glowing.png")
add_entity_to_list("data/entities/animals/wraith_storm.xml","Ukkoshyypiö (Thunder Creep)","enemies","data/ui_gfx/animal_icons/wraith_storm.png")
add_entity_to_list("data/entities/animals/zombie.xml","Hurtta (Hound)","enemies","data/ui_gfx/animal_icons/zombie.png")
add_entity_to_list("data/entities/animals/zombie_weak.xml","Heikkohurtta (Weak Hound)","enemies","data/ui_gfx/animal_icons/zombie_weak.png")

add_entity_to_list("data/entities/animals/illusions/dark_alchemist.xml","Pahn Muisto (Heart Mimic)","enemies","data/ui_gfx/animal_icons/dark_alchemist.png")
add_entity_to_list("data/entities/animals/illusions/shaman_wind.xml","Valhe (Spell refresh mimic)","enemies","data/ui_gfx/animal_icons/shaman_wind.png")





-- bosses
add_entity_to_list("data/entities/animals/boss_centipede/boss_centipede.xml","Kolmisilmä (Three-Eye)","bosses","data/ui_gfx/animal_icons/boss_centipede.png")
add_entity_to_list("data/entities/animals/boss_centipede/boss_centipede_minion.xml","Kolmisilmän apuri (Three-Eye's Helper)","bosses","data/entities/animals/boss_centipede/minion_physics.png")
add_entity_to_list("data/entities/animals/boss_alchemist/boss_alchemist.xml","Ylialkemisti (High Alchemist)","bosses","data/ui_gfx/animal_icons/boss_alchemist.png")
add_entity_to_list("data/entities/animals/parallel/alchemist/parallel_alchemist.xml","Alkemistin Varjo (Alchemist's Shadow)","bosses","data/ui_gfx/animal_icons/parallel_alchemist.png")
add_entity_to_list("data/entities/animals/boss_pit/boss_pit.xml","Sauvojen tuntija (Connoisseur of Wands)","bosses","data/ui_gfx/animal_icons/boss_pit.png")
add_entity_to_list("data/entities/animals/parallel/tentacles/parallel_tentacles.xml","Kolmisilmän Kätyri (Three-eye's Minion)","bosses","data/ui_gfx/animal_icons/parallel_tentacles.png")
add_entity_to_list("data/entities/animals/boss_wizard/boss_wizard.xml","Mestarien mestari (Master of Masters)","bosses","data/ui_gfx/animal_icons/boss_wizard.png")
add_entity_to_list("data/entities/animals/boss_fish/fish_giga.xml","Syväolento (Creature of the Deep)","bosses","data/ui_gfx/animal_icons/fish_giga.png")
add_entity_to_list("data/entities/animals/boss_ghost/boss_ghost.xml","Unohdettu (Forgotten)","bosses","data/ui_gfx/animal_icons/boss_ghost.png")
add_entity_to_list("data/entities/animals/boss_ghost/boss_ghost_polyp.xml","häive (Fade)","bosses","data/ui_gfx/animal_icons/boss_ghost_polyp.png")
add_entity_to_list("data/entities/animals/boss_dragon.xml","Suomuhauki (Dragon)","bosses","data/ui_gfx/animal_icons/boss_dragon.png")
add_entity_to_list("data/entities/animals/boss_limbs/boss_limbs.xml","Kolmisilmän Koipi (Three-Eye's Legs)","bosses","data/ui_gfx/animal_icons/boss_limbs.png")
add_entity_to_list("data/entities/animals/boss_limbs/slimeshooter_boss_limbs.xml","Äitilimanuljaska (Guardian Slime)","bosses","data/entities/animals/ending_placeholder/boss_limbs/slimeshooter_boss.png")
add_entity_to_list("data/entities/animals/boss_robot/boss_robot.xml","Kolmisilmän Silmä (Three-Eye's Eye)","bosses","data/ui_gfx/animal_icons/boss_robot.png")
add_entity_to_list("data/entities/animals/maggot_tiny/maggot_tiny.xml","Limatoukka (Slime Maggot)","bosses","data/ui_gfx/animal_icons/maggot_tiny.png")
add_entity_to_list("data/entities/animals/boss_meat/boss_meat.xml","Kolmisilmän sydän (Three-Eye's Heart)","bosses","data/ui_gfx/animal_icons/boss_meat.png")
add_entity_to_list("data/entities/animals/boss_sky/boss_sky.xml","Kivi (Stone)","bosses","data/ui_gfx/animal_icons/boss_sky.png")
add_entity_to_list("data/entities/animals/boss_spirit/islandspirit.xml","Tapion vasalli (Tapio's Vassal)","bosses","data/ui_gfx/animal_icons/islandspirit.png")
add_entity_to_list("data/entities/animals/boss_gate/gate_monster_c.xml","Mokke (Goalkeeper)","bosses","data/ui_gfx/animal_icons/gate_monster_c.png")
add_entity_to_list("data/entities/animals/boss_gate/gate_monster_b.xml","Molari (Goalkeeper)","bosses","data/ui_gfx/animal_icons/gate_monster_b.png")
add_entity_to_list("data/entities/animals/boss_gate/gate_monster_d.xml","Sevia (Goalkeeper)","bosses","data/ui_gfx/animal_icons/gate_monster_d.png")
add_entity_to_list("data/entities/animals/boss_gate/gate_monster_a.xml","Veska (Goalkeeper)","bosses","data/ui_gfx/animal_icons/gate_monster_a.png")

add_entity_to_list("data/entities/animals/friend.xml","Toveri (Friend)","bosses","data/ui_gfx/animal_icons/friend.png")








